[package]
name = "localdoc_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "localdoc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
directories = "6.0.0"
